adding:
  visibility:
    request_path:
      pages: "/node/*\r\n/news*\r\n/people*\r\n/events*\r\n/event-series*\r\n/publications*\r\n/courses*\r\n/r25/*/calendar"
removing:
  visibility:
    request_path:
      pages: "/node/*\r\n/news*\r\n/people*\r\n/events*\r\n/event-series*\r\n/publications*\r\n/courses*"
